[workspace]
name = "kotatsu"
version = "0.1.0"
description = "A simple C++20 coroutine wrapper for libuv"
authors = ["ykiko <ykikoykikoykiko@gmail.com>"]
license = "Apache-2.0"
license-file = "LICENSE"
readme = "README.md"
documentation = "https://clice.io"
repository = "https://github.com/clice-io/kotatsu"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[environments]
default = ["build"]
linux-gcc = ["build", "linux-gcc"]
linux-clang = ["build", "linux-clang"]
macos-clang = ["build", "macos-clang"]
windows-msvc = ["build", "windows-msvc"]
windows-mingw = ["build", "windows-mingw"]
windows-llvm = ["build", "windows-llvm"]
format = ["format"]

[feature.build.dependencies]
python = "*"
ninja = "*"
ccache = "*"
openssl = "*"

[feature.build.pypi-dependencies]
pygls = ">=2.0"
pytest = ">=8.0"
pytest-asyncio = ">=0.24"

[feature.linux-gcc.target.linux-64.dependencies]
sysroot_linux-64 = "==2.17"
gcc = "==14.2.0"
gxx = "==14.2.0"

[feature.linux-clang.target.linux-64.dependencies]
sysroot_linux-64 = "==2.17"
clang = "==20.1.8"
clangxx = "==20.1.8"
lld = "==20.1.8"
llvm-tools = "==20.1.8"
compiler-rt = "==20.1.8"

[feature.macos-clang.target.osx-arm64.dependencies]
clang = "==20.1.8"
clangxx = "==20.1.8"
lld = "==20.1.8"
llvm-tools = "==20.1.8"
compiler-rt = "==20.1.8"
libcxx = "==20.1.8"

[feature.windows-mingw.target.win-64.dependencies]
gcc = "==14.2.0"
gxx = "==14.2.0"
sccache = "*"

[feature.windows-mingw.target.win-64.activation.env]
PATH = "%CONDA_PREFIX%\\Library\\bin;%PATH%"

[feature.windows-msvc.target.win-64.dependencies]
sccache = "*"

[feature.windows-llvm.target.win-64.dependencies]
clang = "==20.1.8"
clangxx = "==20.1.8"
lld = "==20.1.8"
llvm-tools = "==20.1.8"
compiler-rt = "==20.1.8"
sccache = "*"

[feature.windows-llvm.target.win-64.activation]
scripts = ["scripts/activate_windows_llvm.bat"]

# ============================================================================== #
#                                    FORMAT                                      #
# ============================================================================== #
[feature.format.dependencies]
ruff = "*"
tombi = "*"
stylua = "*"
fd-find = "*"
prettier = "*"
clang-format = "==21.1.8"

[feature.format.tasks]
format-cpp = "fd -H -e cpp -e h -e cc -e hpp -E include/kota/ipc/lsp/protocol.h -x clang-format -i"
format-python = "ruff format ."
format-lua = "stylua ."
format-web = "fd -H -e js -e ts -e css -x prettier --write"
format-markdown = "fd -H -e md -x prettier --write"
format-json = "fd -H -e json -E package-lock.json -E .git -x prettier --write"
format-toml = "fd -H -e toml -x tombi format"
format-yaml = """
fd -H -e yaml -e yml -E pnpm-lock.yaml -x prettier --write && \
fd -H "^\\.clang-(format|tidy)$" -x prettier --write --parser yaml
"""
format = { depends-on = [
    "format-cpp",
    "format-python",
    "format-lua",
    "format-web",
    "format-markdown",
    "format-json",
    "format-toml",
    "format-yaml"
] }

[feature.format.target.win-64.tasks]
format-web = "fd -H -e js -e ts -e css -x prettier.bat --write"
format-markdown = "fd -H -e md -x prettier.bat --write"
format-json = "fd -H -e json -E package-lock.json -E .git -x prettier.bat --write"
format-yaml = """
fd -H -e yaml -e yml -E pnpm-lock.yaml -x prettier.bat --write && \
fd -H "^\\.clang-(format|tidy)$" -x prettier.bat --write --parser yaml
"""

[tasks]
xmake-test = "xmake test --verbose"
xmake-build = "xmake --all --verbose --diagnosis"
integration-test = "pytest tests/integration/ -v"

[tasks.ci-xmake-configure]
args = ["build_type"]
cmd = "xmake config --clean --yes --mode={{ build_type }}{% if pixi.is_osx %} --toolchain=clang{% endif %}"

[tasks.ci-xmake-build]
args = ["build_type"]
depends-on = [
    { task = "ci-xmake-configure", args = ["{{ build_type }}"] },
    { task = "xmake-build" },
    { task = "xmake-test" },
]
